# =====================================================
# Bipolar — Medication Tracker
# Multi-stage Dockerfile for Next.js 15 standalone build
# =====================================================

# ---------- Stage 1: deps ----------
FROM node:20-alpine AS deps
WORKDIR /app

# Install build tools needed for better-sqlite3 native compilation
# (only needed if prebuilt binaries are not available for alpine-musl)
RUN apk add --no-cache python3 make g++

COPY package.json package-lock.json* ./
RUN npm ci

# ---------- Stage 2: builder ----------
FROM node:20-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

RUN npm run build

# ---------- Stage 3: runner ----------
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV TZ=America/Montevideo
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Install tzdata + wget (for healthcheck) and set Uruguay timezone
RUN apk add --no-cache tzdata wget && \
    cp /usr/share/zoneinfo/America/Montevideo /etc/localtime && \
    echo "America/Montevideo" > /etc/timezone

# Non-root user for security
RUN addgroup --system --gid 1001 bipolar && \
    adduser --system --uid 1001 bipolar

# Copy Next.js standalone output
COPY --from=builder /app/public ./public
COPY --from=builder --chown=bipolar:bipolar /app/.next/standalone ./
COPY --from=builder --chown=bipolar:bipolar /app/.next/static ./.next/static

# Copy Drizzle migrations (run at container startup)
COPY --from=builder --chown=bipolar:bipolar /app/drizzle ./drizzle

# Data directory — mounted as a volume at runtime
RUN mkdir -p /app/data/audio /app/data/reports && \
    chown -R bipolar:bipolar /app/data

USER bipolar
EXPOSE 3000

# server.js is generated by Next.js standalone output
# It should internally:
#   1. Run drizzle migrations
#   2. Seed admin if not exists
#   3. Start the Next.js server
#   4. Start node-cron jobs (daily status + retry poller)
CMD ["node", "server.js"]
